version: "2"

services:
    php:
        build:
            context: ./docker/php
            args:
                PHP_XDEBUG_INSTALL: ${DOCKER_BUILD_ARG_PHP_XDEBUG_INSTALL}
                PHP_XDEBUG_DEFAULT_ENABLE: ${DOCKER_BUILD_ARG_PHP_XDEBUG_DEFAULT_ENABLE}
                PHP_XDEBUG_COVERAGE_ENABLE: ${DOCKER_BUILD_ARG_PHP_XDEBUG_COVERAGE_ENABLE}
                PHP_XDEBUG_REMOTE_ENABLE: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_ENABLE}
                PHP_XDEBUG_REMOTE_AUTO_START: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_AUTO_START}
                PHP_XDEBUG_REMOTE_CONNECT_BACK: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_CONNECT_BACK}
                PHP_XDEBUG_REMOTE_HOST: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_HOST}
                PHP_XDEBUG_REMOTE_PORT: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_PORT}
                PHP_XDEBUG_IDEKEY: ${DOCKER_BUILD_ARG_PHP_XDEBUG_IDEKEY}
                PHP_XDEBUG_PROFILER_ENABLE: ${DOCKER_BUILD_ARG_PHP_XDEBUG_PROFILER_ENABLE}
                PHP_XDEBUG_PROFILER_OUTPUT_DIR: ${DOCKER_BUILD_ARG_PHP_XDEBUG_PROFILER_OUTPUT_DIR}
        ports:
            - 8080:80
        volumes:
            - .:/work:cached
            # exclude volumes
            - /work/.git/
            - /work/docker/
            - /work/logs/
            - /work/build/
        environment:
            TZ: Asia/Tokyo
    postgres:
        image: postgres:9.4-alpine
        ports:
            - 5432:5432
        environment:
          POSTGRES_PASSWORD: secret
