version: "2"

services:
    php:
        build:
            context: ./docker/php
        ports:
            - 8080:80
        volumes:
            - .:/work:cached
            # exclude volumes
            - /work/.git/
            - /work/docker/
            - /work/logs/
            - /work/build/
        environment:
            TZ: Asia/Tokyo
    postgres:
        image: postgres:9.4-alpine
        ports:
            - 5432:5432
        environment:
          POSTGRES_PASSWORD: secret
